#!/bin/bash
# server mysql backup

# backup init
dir=/home/
user=root
pwd=
server=admin
database=
date=`date +%Y_%m_%d`
filename="$server"_"$date".sql

#Script for exec
cd $dir
mysqldump -u $user -p$pwd --skip-lock-tables $database > "$filename"
find $dir -type f -mtime +3 -delete;
